### ISSUE TITLE
Problems when upgrade to version 0.6.0

### ISSUE THREAD

**Issue by NewEra2063** [noia-network/noia-node-gui#53]
Hi,

I have been using  3 nodes of NOIA in testnet since July.

Today a tried to upgrade one machine from version 0.5.0 to version 0.6.0 but it does not work.

At this machine a have a clean Windows 8.1 enterprise Build 9600 with all patchs (this machine is old and has a resolution of 1024 x 600)

Running the 0.5.0 its ok,

After install a 0.6.0 I started the application and it does not show the application interface, but if o open the task manager I can see 2 instances of noia opened (with no consume of CPU or Disk).

Could you help me with this issue?

Best regards,

![image](https://user-images.githubusercontent.com/42708848/44625094-442c7780-a8d7-11e8-8c45-60e24fe824c0.png)

After the upgrade to 0.6.0

![image](https://user-images.githubusercontent.com/42708848/44625126-cfa60880-a8d7-11e8-87d1-2cfac6b1043e.png)

**Comment by Dancia** [comment]
Are you sure the application didn't minimize to tray?

![image](https://user-images.githubusercontent.com/8902599/44626052-b1173000-a91e-11e8-97c3-7758ce6e4fdd.png)

**Comment by NewEra2063** [comment]
Hi,

Yes, I am sure. You can see in this scream short.

![image](https://user-images.githubusercontent.com/42708848/44634017-da10e280-a969-11e8-90b4-247c36bfb8c2.png)

**Comment by MartynasZilinskas** [comment]
@NewEra2063 Could you run from command line `NOIA.exe` and write log output here.

**Comment by NewEra2063** [comment]
Hi,

Here it is.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd \

C:\>cd C:\Users\Admin\AppData\Local\Programs\noia-node-gui

C:\Users\Admin\AppData\Local\Programs\noia-node-gui>noia.exe

C:\Users\Admin\AppData\Local\Programs\noia-node-gui>
←[31merror←[39m: [noia-contents-client] uncaughtException: \\?\C:\Users\Admin\Ap
pData\Local\Temp\d81c98a8-b918-40e8-b595-bdbc42218510.tmp.node is not a valid Wi
n32 application\\?\C:\Users\Admin\AppData\Local\Temp\d81c98a8-b918-40e8-b595-bdb
c42218510.tmp.node date=Tue Aug 28 2018 00:02:19 GMT-0300 (E. South America Stan
dard Time), pid=2948, uid=null, gid=null, cwd=C:\Users\Admin\AppData\Local\Progr
ams\noia-node-gui, execPath=C:\Users\Admin\AppData\Local\Programs\noia-node-gui\
NOIA.exe, version=v8.9.3, argv=[C:\Users\Admin\AppData\Local\Programs\noia-node-
gui\NOIA.exe], rss=48541696, heapTotal=29560832, heapUsed=10683372, external=200
926, loadavg=[0, 0, 0], uptime=295.840878, trace=[column=20, file=ELECTRON_ASAR.
js, function=process.module.(anonymous function) [as dlopen], line=172, method=(
anonymous function) [as dlopen], native=false, column=18, file=module.js, functi
on=Module._extensions..node, line=671, method=.node, native=false, column=18, fi
le=ELECTRON_ASAR.js, function=Object.module.(anonymous function) [as .node], lin
e=186, method=node], native=false, column=32, file=module.js, function=Module.lo
ad, line=561, method=load, native=false, column=12, file=module.js, function=try
ModuleLoad, line=504, method=null, native=false, column=3, file=module.js, funct
ion=Module._load, line=496, method=_load, native=false, column=17, file=module.j
s, function=Module.require, line=586, method=require, native=false, column=18, f
ile=internal/module.js, function=require, line=11, method=null, native=false, co
lumn=10, file=C:\Users\Admin\AppData\Local\Programs\noia-node-gui\resources\app.
asar\node_modules\node-cmake\index.js, function=requireNativeModule, line=41, me
thod=null, native=false, column=39, file=C:\Users\Admin\AppData\Local\Programs\n
oia-node-gui\resources\app.asar\node_modules\wrtc\lib\binding.js, function=null,
 line=3, method=null, native=false], stack=[Error: \\?\C:\Users\Admin\AppData\Lo
cal\Temp\d81c98a8-b918-40e8-b595-bdbc42218510.tmp.node is not a valid Win32 appl
ication\\?\C:\Users\Admin\AppData\Local\Temp\d81c98a8-b918-40e8-b595-bdbc4221851
0.tmp.node,     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASA
R.js:172:20),     at Object.Module._extensions..node (module.js:671:18),     at
Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18),     at
Module.load (module.js:561:32),     at tryModuleLoad (module.js:504:12),     at
Function.Module._load (module.js:496:3),     at Module.require (module.js:586:17
),     at require (internal/module.js:11:18),     at requireNativeModule (C:\Use
rs\Admin\AppData\Local\Programs\noia-node-gui\resources\app.asar\node_modules\no
de-cmake\index.js:41:10),     at Object.<anonymous> (C:\Users\Admin\AppData\Loca
l\Programs\noia-node-gui\resources\app.asar\node_modules\wrtc\lib\binding.js:3:3
9)]



![image](https://user-images.githubusercontent.com/42708848/44698414-29ccd800-aa56-11e8-8a99-54f433ebf62b.png)

**Comment by MartynasZilinskas** [comment]
@NewEra2063 32-bit or 64-bit? Because at the moment wrtc dependency that we are using only supports 64-bit. https://github.com/noia-network/noia-node-cli/issues/8#issuecomment-416000777

**Comment by NewEra2063** [comment]
Hi,

32-bit. :-(

Are you planning to have a release to 32 bits?

Thanks in advanced.

**Comment by jubilee62** [comment]
I tried putting NOIA gui onto an old laptop I upgraded to Windows 7 - 32 bit - but GUI is hung - won't start - no message.
