### ISSUE TITLE
Error when updating from 0.6.0 to 0.6.2

### ISSUE THREAD

**Issue by luchmedia** [noia-network/noia-node-gui#56]
I started gui node (version 0.6.0), it notified me that there was a newer version (0.6.2), when i clicked to update it returned me this error:

`error: [noia-node]  message=No server found, verify your proxy/network, stack=Error: No server found, verify your proxy/network
    at gotServers (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:621:25)
    at /tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:107:16
    at /tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:301:7
    at Parser.<anonymous> (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.exports.Parser.Parser.parseString (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/xml2js/lib/parser.js:313:16)
    at Parser.parseString (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/xml2js/lib/parser.js:354:19)
    at /tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:299:5
    at /tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:107:16
    at IncomingMessage.<anonymous> (/tmp/.mount_noia-n8MqDNJ/resources/app.asar/node_modules/speedtest-net/index.js:175:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:19344) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by MartynasZilinskas** [comment]
Did you still received error?
